{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "OpenShift Service Mesh 1",
      "fix_state": "Affected",
      "package_name": "servicemesh-proxy",
      "cpe": "cpe:/a:redhat:service_mesh:1"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2020-06-30T19:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-8663 envoy: Resource exhaustion when accepting too many connections",
    "id": "1844254",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1844254"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "A uncontrolled resource consumption vulnerability was found in Envoy. An attacker can initiate too many connections to the proxy potentially exhausting file descriptors and/or memory resulting in a denial of service.",
  "acknowledgement": "Red Hat would like to thank the Envoy security team for reporting this issue.",
  "name": "CVE-2020-8663",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://istio.io/latest/news/security/istio-security-2020-007/"
  ]
}