{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Out of support scope",
      "package_name": "NetworkManager",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "NetworkManager",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "NetworkManager",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "NetworkManager",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-05-29T04:41:00Z",
  "bugzilla": {
    "description": "CVE-2020-10754 NetworkManager: user configuration not honoured leaving the connection unauthenticated via insecure defaults",
    "id": "1841041",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1841041"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "4.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-287-\u003eCWE-306",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-10754",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}