{
  "Severity": "CRITICAL",
  "UpdatedAt": "2020-03-06T20:12:00Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "requests-kerberos"
  },
  "Advisory": {
    "DatabaseId": 1975,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXdoMzctMzd4dy01NGhy",
    "GhsaId": "GHSA-wh37-37xw-54hr",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2014-8650"
      },
      {
        "Url": "https://github.com/advisories/GHSA-wh37-37xw-54hr"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-wh37-37xw-54hr"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2014-8650"
      }
    ],
    "Description": "python-requests-Kerberos through 0.5 does not handle mutual authentication",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2020-03-10T18:02:31Z",
    "Severity": "CRITICAL",
    "Summary": "Improper Authentication in requests-kerberos",
    "UpdatedAt": "2020-03-10T18:02:31Z",
    "WithdrawnAt": ""
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "0.6"
      },
      "VulnerableVersionRange": "\u003c 0.5"
    }
  ]
}