{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-7698"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "This affects the package Gerapy from 0 and before 0.9.3. The input being passed to Popen, via the project_configure endpoint, isnâ€™t being sanitized."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/Gerapy/Gerapy/commit/e8446605eb2424717418eae199ec7aad573da2d2",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/Gerapy/Gerapy/commit/e8446605eb2424717418eae199ec7aad573da2d2"
        },
        {
          "name": "https://snyk.io/vuln/SNYK-PYTHON-GERAPY-572470",
          "refsource": "MISC",
          "tags": [],
          "url": "https://snyk.io/vuln/SNYK-PYTHON-GERAPY-572470"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-07-29T13:23Z",
  "publishedDate": "2020-07-29T13:15Z"
}