{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-13846"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Sylabs Singularity 3.5.0 through 3.5.3 fails to report an error in a Status Code."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/hpcng/singularity/security/advisories/GHSA-6w7g-p4jh-rf92",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/hpcng/singularity/security/advisories/GHSA-6w7g-p4jh-rf92"
        },
        {
          "name": "https://medium.com/sylabs",
          "refsource": "MISC",
          "tags": [],
          "url": "https://medium.com/sylabs"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-07-14T21:05Z",
  "publishedDate": "2020-07-14T18:15Z"
}