{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-10028"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Multiple syscalls with insufficient argument validation See NCC-ZEP-006 This issue affects: zephyrproject-rtos zephyr version 1.14.0 and later versions. version 2.1.0 and later versions."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://docs.zephyrproject.org/latest/security/vulnerabilities.html#CVE-2020-10028",
          "refsource": "MISC",
          "tags": [],
          "url": "https://docs.zephyrproject.org/latest/security/vulnerabilities.html#CVE-2020-10028"
        },
        {
          "name": "https://github.com/zephyrproject-rtos/zephyr/pull/23308",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/zephyrproject-rtos/zephyr/pull/23308"
        },
        {
          "name": "https://github.com/zephyrproject-rtos/zephyr/pull/23733",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/zephyrproject-rtos/zephyr/pull/23733"
        },
        {
          "name": "https://github.com/zephyrproject-rtos/zephyr/pull/23737",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/zephyrproject-rtos/zephyr/pull/23737"
        },
        {
          "name": "https://zephyrprojectsec.atlassian.net/browse/ZEPSEC-32",
          "refsource": "MISC",
          "tags": [],
          "url": "https://zephyrprojectsec.atlassian.net/browse/ZEPSEC-32"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-05-12T12:12Z",
  "publishedDate": "2020-05-11T23:15Z"
}