{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [
          {
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:pulsesecure:pulse_connect_secure:*:*:*:*:*:*:*:*",
                "versionEndIncluding": "2020-04-06",
                "vulnerable": true
              }
            ],
            "operator": "OR"
          },
          {
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:o:apple:mac_os:-:*:*:*:*:*:*:*",
                "vulnerable": false
              },
              {
                "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:-:*:*:*:*:*:*:*",
                "vulnerable": false
              },
              {
                "cpe23Uri": "cpe:2.3:o:oracle:solaris:-:*:*:*:*:*:*:*",
                "vulnerable": false
              }
            ],
            "operator": "OR"
          }
        ],
        "operator": "AND"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-11580"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "pulse_connect_secure",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "\u003c=",
                        "version_value": "2020-04-06"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "pulsesecure"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue was discovered in Pulse Secure Pulse Connect Secure (PCS) through 2020-04-06. The applet in tncc.jar, executed on macOS, Linux, and Solaris clients when a Host Checker policy is enforced, accepts an arbitrary SSL certificate."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-295"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://git.lsd.cat/g/pulse-host-checker-rce",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Third Party Advisory"
          ],
          "url": "https://git.lsd.cat/g/pulse-host-checker-rce"
        },
        {
          "name": "https://kb.pulsesecure.net/articles/Pulse_Security_Advisories/SA44426",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://kb.pulsesecure.net/articles/Pulse_Security_Advisories/SA44426"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 6.4,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:N",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2020-04-08T21:15Z",
  "publishedDate": "2020-04-06T21:15Z"
}