{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-11538"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In libImaging/SgiRleDecode.c in Pillow through 7.0.0, a number of out-of-bounds reads exist in the parsing of SGI image files, a different issue than CVE-2020-5311."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/python-pillow/Pillow/pull/4504",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python-pillow/Pillow/pull/4504"
        },
        {
          "name": "https://github.com/python-pillow/Pillow/pull/4538",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python-pillow/Pillow/pull/4538"
        },
        {
          "name": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html",
          "refsource": "MISC",
          "tags": [],
          "url": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html"
        },
        {
          "name": "https://pillow.readthedocs.io/en/stable/releasenotes/index.html",
          "refsource": "MISC",
          "tags": [],
          "url": "https://pillow.readthedocs.io/en/stable/releasenotes/index.html"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-06-25T19:31Z",
  "publishedDate": "2020-06-25T19:15Z"
}