{
  "Severity": "MODERATE",
  "UpdatedAt": "2020-06-04T18:32:37Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "django"
  },
  "Advisory": {
    "DatabaseId": 2140,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXdwanItajU3eC13eGZ3",
    "GhsaId": "GHSA-wpjr-j57x-wxfw",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2020-13254"
      },
      {
        "Url": "https://github.com/advisories/GHSA-wpjr-j57x-wxfw"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-wpjr-j57x-wxfw"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2020-13254"
      }
    ],
    "Description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2020-06-05T16:20:44Z",
    "Severity": "MODERATE",
    "Summary": "Data leakage via cache key collision in Django",
    "UpdatedAt": "2020-06-05T16:20:44Z",
    "WithdrawnAt": ""
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "3.0.7"
      },
      "VulnerableVersionRange": "\u003e= 3.0.0, \u003c 3.0.7"
    },
    {
      "FirstPatchedVersion": {
        "Identifier": "2.2.13"
      },
      "VulnerableVersionRange": "\u003e= 2.0.0, \u003c 2.2.13"
    }
  ]
}