{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2013-7489"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The Beaker library through 1.11.0 for Python is affected by deserialization of untrusted data, which could lead to arbitrary code execution."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1850105",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1850105"
        },
        {
          "name": "https://github.com/bbangert/beaker/issues/191",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/bbangert/beaker/issues/191"
        },
        {
          "name": "https://www.openwall.com/lists/oss-security/2020/05/14/11",
          "refsource": "MISC",
          "tags": [],
          "url": "https://www.openwall.com/lists/oss-security/2020/05/14/11"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-06-26T20:31Z",
  "publishedDate": "2020-06-26T20:15Z"
}