{
  "description": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
  "releases": {
    "bullseye": {
      "fixed_version": "0",
      "repositories": {
        "bullseye": "2:2.2.12-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "buster": {
      "fixed_version": "0",
      "repositories": {
        "buster": "1:1.11.28-1~deb10u1",
        "buster-security": "1:1.11.28-1~deb10u1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "jessie": {
      "fixed_version": "0",
      "repositories": {
        "jessie": "1.7.11-1+deb8u3",
        "jessie-security": "1.7.11-1+deb8u9"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "sid": {
      "fixed_version": "0",
      "repositories": {
        "sid": "2:2.2.13-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "stretch": {
      "fixed_version": "0",
      "repositories": {
        "stretch": "1:1.10.7-2+deb9u7",
        "stretch-security": "1:1.10.7-2+deb9u8"
      },
      "status": "resolved",
      "urgency": "unimportant"
    }
  },
  "scope": "local"
}